# General Jekyll Config
pygments: true
auto: true
url: http://whitmanschorn.com
lsi: false
markdown: kramdown
exclude: [LICENSE, CNAME, README.md, .gitignore]

# Site settings
title: Whitman Schorn
tag_text: Whitman Schorn
description: A developer working in web, mobile, and AR/VR experiences and applications.

sass:
  style: compressed
