# General Jekyll Config
pygments: true
auto: true
url: http://whitmanschorn.com
lsi: false
markdown: kramdown
exclude: [LICENSE, CNAME, README.md, .gitignore]

# Site settings
title: Whitman Schorn
tag_text: Whitman Schorn
description: Solo is a Jekyll theme that supports single-page websites only, but supports them well. Yes, it’s responsive.

sass:
  style: compressed
