# General Jekyll Config
pygments: true
auto: true
url: http://wschorn.com
lsi: false
markdown: kramdown
exclude: [LICENSE, CNAME, README.md, .gitignore]

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#019875'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: wschorn
    twitter: what_whit
    linkedin: wschorn


  # "Hi, I'm _______"
  name: frontendery
  email: whit.schorn@gmail.com

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-45568047-1

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
